In [3]:
# Database Connectivity

import mysql.connector

mydb=mysql.connector.connect(
    host="localhost",
    user="root",
    password=""
)

mycursor=mydb.cursor()
mycursor.execute("Create Database mydbs")

In [4]:
import mysql.connector

mydb=mysql.connector.connect(
    host="localhost",
    user="root",
    password=""
)

mycursor=mydb.cursor()
mycursor.execute("SHOW DATABASES")

for x in mycursor:
    print(x)

('information_schema',)
('mydatabase',)
('mydbs',)
('mysql',)
('performance_schema',)
('phpmyadmin',)
('test',)


In [6]:
import mysql.connector

mydb=mysql.connector.connect(
    host="localhost",
    user="root",
    password="",
    database="mydbs"
)

mycursor=mydb.cursor()
mycursor.execute("Create table Students (id INT AUTO_INCREMENT PRIMARY KEY,name varchar(244),address varchar (300))")

In [7]:
import mysql.connector

mydb=mysql.connector.connect(
    host="localhost",
    user="root",
    password="",
    database="mydbs"
)

mycursor=mydb.cursor()
mycursor.execute("Show Tables")

for x in mycursor:
    print(x)

('students',)


In [9]:
import mysql.connector

mydb=mysql.connector.connect(
    host="localhost",
    user="root",
    password="",
    database="mydbs"
)

mycursor=mydb.cursor()

sql="insert into Students (Name,Address) values(%s,%s)"
val=("Arya","KKK")

mycursor.execute(sql,val)

mydb.commit()

print(mycursor.rowcount,"record inserted.")

1 record inserted.


In [14]:
import mysql.connector

mydb=mysql.connector.connect(
    host="localhost",
    user="root",
    password="",
    database="mydbs"

)

mycursor=mydb.cursor()

mycursor.execute("Update Students set Name='Rishi' where name='Arya'")

mydb.commit()

print(mycursor.rowcount,"Record updated")
                 

1 Record updated


In [15]:
import mysql.connector

mydb=mysql.connector.connect(
    host="localhost",
    user="root",
    password="",
    database="mydbs"

)

mycursor=mydb.cursor()

mycursor.execute("Delete from Students where Name='Rishi'")

mydb.commit()



In [18]:
import mysql.connector

mydb=mysql.connector.connect(
    host="localhost",
    user="root",
    password="",
    database="mydbs"
)

mycursor=mydb.cursor()

sql="insert into Students (Name,Address) values(%s,%s)"
val=[
    ('Arya','KKK'),
    ('Ramu','KKO'),
    ('Jino','UYY'),
    ('Jeru','RTY')
]

mycursor.executemany(sql,val)

mydb.commit()

print(mycursor.rowcount,"record inserted.")

4 record inserted.


In [19]:
import mysql.connector

mydb=mysql.connector.connect(
    host="localhost",
    user="root",
    password="",
    database="mydbs"
)

mycursor=mydb.cursor()

mycursor.execute("Select * from Students")

myresult=mycursor.fetchall()


for x in myresult:
    print(x)

(2, 'Arya', 'KKK')
(3, 'Ramu', 'KKO')
(4, 'Jino', 'UYY')
(5, 'Jeru', 'RTY')


In [24]:
# 4.1.1.	Create a numpy array filled with all ones by defining its shape.

import numpy as np

a=np.ones(1,dtype=int)
print(a)
b=np.ones(2,dtype=int)
print(b)
c=np.ones(3,dtype=int)
print(c)

[1]
[1 1]
[1 1 1]


In [36]:
# 4.1.2.	How do you remove rows from a Numpy array that contains non-numeric values

import numpy as np

n_arr=np.array([[12,23,45,90],[67,np.nan,np.nan,np.nan]])
print(n_arr)

print(n_arr[~np.isnan(n_arr).any(axis=1)])


[[12. 23. 45. 90.]
 [67. nan nan nan]]
[[12. 23. 45. 90.]]


In [47]:
# 4.1.3.	Remove single-dimensional entries from the shape of an array

import numpy as np

in_arr=np.arange(9).reshape(1,3,3)
print(in_arr)

op_arr=np.squeeze(in_arr,axis=0)
print(op_arr)

print("The shape is: ",in_arr.shape,op_arr.shape)

[[[0 1 2]
  [3 4 5]
  [6 7 8]]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
The shape is:  (1, 3, 3) (3, 3)


In [50]:
# How do you check whether specified values are present in the NumPy array?

import numpy as np

arr=np.array([[10,20,30],[40,50,60]])

print(arr)

print(20 in arr)
print(59 in arr)

[[10 20 30]
 [40 50 60]]
True
False


In [51]:
# Handle the given dataset (Data.csv) with adequate preprocessing steps mentioned and visualize the dataset with appropriate graphs.
# Handle Missing Data Values
# Encode the categorical data
# Scale your features


import pandas as pd

df=pd.read_csv('Data.csv')
print(df)

      Country   Age   Salary Purchased
0       India  34.0  92000.0       Yes
1   Sri lanka  22.0  25000.0       Yes
2       China  31.0  74000.0       Yes
3   Sri lanka  29.0      NaN        No
4       China  55.0  98000.0       Yes
5       India  24.0  30000.0        No
6   Sri lanka  28.0  40000.0        No
7       India   NaN  60000.0        No
8       China  51.0  89000.0       Yes
9       India  44.0  78000.0       Yes
10  Sri lanka  21.0  20000.0        No
11      China  25.0  30000.0       Yes
12      India  33.0  45000.0       Yes
13      India  42.0  65000.0       Yes
14  Sri lanka  33.0  22000.0        No


In [60]:
x=df.iloc[:,-1].values

In [61]:
print(x)

['Yes' 'Yes' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'Yes'
 'Yes' 'No']


In [62]:
y=df.iloc[:,3].values

In [63]:
print(y)

['Yes' 'Yes' 'Yes' 'No' 'Yes' 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'Yes'
 'Yes' 'No']


In [68]:
pip install scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [117]:
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split

In [118]:

import pandas as pd

df=pd.read_csv('Data.csv')
print(df)

      Country   Age   Salary Purchased
0       India  34.0  92000.0       Yes
1   Sri lanka  22.0  25000.0       Yes
2       China  31.0  74000.0       Yes
3   Sri lanka  29.0      NaN        No
4       China  55.0  98000.0       Yes
5       India  24.0  30000.0        No
6   Sri lanka  28.0  40000.0        No
7       India   NaN  60000.0        No
8       China  51.0  89000.0       Yes
9       India  44.0  78000.0       Yes
10  Sri lanka  21.0  20000.0        No
11      China  25.0  30000.0       Yes
12      India  33.0  45000.0       Yes
13      India  42.0  65000.0       Yes
14  Sri lanka  33.0  22000.0        No


In [76]:
# imputer=SimpleImputer(missing_values='Nan',strategy="mean")

In [119]:
# print(df)

In [112]:
# X=df.drop('Purchased',axis=1)
# y=df['Purchased']

In [114]:
# print(X)
# print(y)

In [130]:
# df=pd.get_dummies(df,columns=['Purchased_Yes_1'],drop_first=True)
# print(df.columns)

In [115]:
# num_col=['Age','Salary']
# categorical_col=['Country','Puchased']

In [85]:
# num_transforms=Pipeline(steps=[
#     ('imputer',SimpleImputer(strategy='mean')),
#     ('scaler',StandardScaler)
# ])

# cate_transforms=Pipeline(steps=[
#     ('imputer',SimpleImputer(strategy='most_frequent')),
#     ('onehot',OneHotEncoder(handle_unknown='ignore'))
# ])

In [94]:
# preprocessor=ColumnTransformer(
#     transformers=[
#         ('num',num_transforms,num_col),
#         ('cat',cate_transforms,categorical_col)
#     ])

In [89]:
# from sklearn.ensemble import RandomForestClassifier
# model=RandomForestClassifier()

In [95]:
# clf=Pipeline(steps=[('preprocessor',preprocessor),('classifier',model)])


In [100]:
# X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [102]:
# df=pd.get_dummies(df,columns=['Purchased'],drop_first=True)

In [110]:
# print(df)