In [1]:
import numpy as np

# Define two matrices A and B
A = np.array([[1, 2, 3],
              [4, 5, 6]])

B = np.array([[7, 8],
              [9, 10],
              [11, 12]])

# Perform matrix multiplication using np.dot()
result = np.dot(A, B)

# Alternatively, you can use the @ operator for matrix multiplication
# result = A @ B

# Display the result
print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nResult of Matrix Multiplication A * B:")
print(result)


Matrix A:
[[1 2 3]
 [4 5 6]]

Matrix B:
[[ 7  8]
 [ 9 10]
 [11 12]]

Result of Matrix Multiplication A * B:
[[ 58  64]
 [139 154]]


In [2]:
import numpy as np

# Define two matrices A and B with complex numbers
A = np.array([[1 + 2j, 3 + 4j],
              [5 + 6j, 7 + 8j]])

B = np.array([[9 + 10j, 11 + 12j],
              [13 + 14j, 15 + 16j]])

# Perform matrix multiplication using np.dot()
result = np.dot(A, B)

# Alternatively, you can use the @ operator for matrix multiplication
# result = A @ B

# Display the result
print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nResult of Matrix Multiplication A * B:")
print(result)


Matrix A:
[[1.+2.j 3.+4.j]
 [5.+6.j 7.+8.j]]

Matrix B:
[[ 9.+10.j 11.+12.j]
 [13.+14.j 15.+16.j]]

Result of Matrix Multiplication A * B:
[[-28.+122.j -32.+142.j]
 [-36.+306.j -40.+358.j]]


In [3]:
import numpy as np

# Define two vectors
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

# Calculate the inner product (dot product)
inner_product = np.dot(vector1, vector2)

# Alternatively, you can use the "@" operator for dot product
# inner_product = vector1 @ vector2

print("Inner Product (Dot Product):", inner_product)


Inner Product (Dot Product): 32


In [4]:
import numpy as np

# Define two vectors
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

# Calculate the outer product (tensor product)
outer_product = np.outer(vector1, vector2)

print("Outer Product (Tensor Product):\n", outer_product)


Outer Product (Tensor Product):
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [5]:
import numpy as np

# Define two 3D vectors
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

# Calculate the cross product (vector product)
cross_product = np.cross(vector1, vector2)

print("Cross Product (Vector Product):\n", cross_product)


Cross Product (Vector Product):
 [-3  6 -3]


In [6]:
import numpy as np

# Define two NumPy arrays (you can replace these with your own data)
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([5, 4, 3, 2, 1])

# Compute the covariance matrix
covariance_matrix = np.cov(array1, array2)

print("Covariance Matrix:\n", covariance_matrix)


Covariance Matrix:
 [[ 2.5 -2.5]
 [-2.5  2.5]]


In [7]:
import numpy as np

# Define the covariance matrix (replace with your own data)
covariance_matrix = np.array([[1.0, 2.0],
                              [2.0, 4.0]])

# Calculate the standard deviations of the variables
std_devs = np.sqrt(np.diag(covariance_matrix))

# Calculate the correlation matrix
correlation_matrix = covariance_matrix / np.outer(std_devs, std_devs)

print("Covariance Matrix:\n", covariance_matrix)
print("\nStandard Deviations:", std_devs)
print("\nCorrelation Matrix:\n", correlation_matrix)


Covariance Matrix:
 [[1. 2.]
 [2. 4.]]

Standard Deviations: [1. 2.]

Correlation Matrix:
 [[1. 1.]
 [1. 1.]]
